services:
  db:
    image: postgres:16.2
    container_name: pettech_db
    environment:
      POSTGRES_DB: pettech
      POSTGRES_USER: pettech_user
      POSTGRES_PASSWORD: pettech_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pettech_network
    restart: unless-stopped

  backend:
    build:
      context: .
    container_name: pettech_backend
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
      DJANGO_SETTINGS_MODULE: config.settings.development
      DB_HOST: db
    volumes:
      - .:/app
      - pettech_media:/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - pettech_network
    restart: on-failure

networks:
  pettech_network:
    driver: bridge

volumes:
  postgres_data:
  pettech_media:
