# SonarCloud Configuration — Backend
sonar.projectKey=mr-leja_PetTech-backend
sonar.projectName=PetTech-backend
sonar.organization=mr-leja-1


sonar.sources=apps,core
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/admin.py,**/apps.py,manage.py,start.py


sonar.tests=apps
sonar.test.inclusions=apps/**/tests/**/*.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12

# Excluir migraciones, admin y config del análisis de cobertura
sonar.coverage.exclusions=**/migrations/**,apps/*/admin.py,apps/*/apps.py,manage.py,start.py,config/**

# Metadata
sonar.sourceEncoding=UTF-8
