# Generated by Django 5.0.6 on 2026-03-26 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioVacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.TextField(blank=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('adopcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendario', to='adopciones.adopcion')),
            ],
            options={
                'verbose_name': 'Calendario de Vacunación',
                'verbose_name_plural': 'Calendarios de Vacunación',
                'db_table': 'calendarios_vacunacion',
            },
        ),
        migrations.CreateModel(
            name='EntradaCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vacuna', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_sugerida', models.DateField()),
                ('es_refuerzo', models.BooleanField(default=False)),
                ('completada', models.BooleanField(default=False)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='adopciones.calendariovacunacion')),
            ],
            options={
                'verbose_name': 'Entrada de Calendario',
                'verbose_name_plural': 'Entradas de Calendario',
                'db_table': 'entradas_calendario',
                'ordering': ['fecha_sugerida'],
            },
        ),
    ]
