# Generated by Django 5.0.6 on 2026-03-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionesHogar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vivienda', models.CharField(choices=[('CASA', 'Casa'), ('APARTAMENTO', 'Apartamento'), ('FINCA', 'Finca'), ('OTRO', 'Otro')], max_length=15)),
                ('tiene_patio', models.BooleanField(default=False)),
                ('numero_personas', models.PositiveSmallIntegerField()),
                ('tiene_mascotas_actualmente', models.BooleanField(default=False)),
                ('experiencia_mascotas', models.TextField(blank=True)),
                ('acuerdo_responsabilidad', models.BooleanField(default=False, help_text='Usuario aceptó el acuerdo de responsabilidad (HU-05)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Condiciones del Hogar',
                'verbose_name_plural': 'Condiciones del Hogar',
                'db_table': 'condiciones_hogar',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_familia', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
                'db_table': 'familias',
            },
        ),
    ]
