# Generated by Django 5.0.6 on 2026-03-24 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('familias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='familia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='condicioneshogar',
            name='familia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones_hogar', to='familias.familia'),
        ),
    ]
