# Generated by Django 5.0.6 on 2026-03-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicioneshogar',
            name='ingresos_estimados',
            field=models.CharField(blank=True, choices=[('MENOS_1SMLV', 'Menos de 1 SMLV'), ('1_2SMLV', '1–2 SMLV'), ('2_4SMLV', '2–4 SMLV'), ('MAS_4SMLV', 'Más de 4 SMLV')], max_length=30),
        ),
        migrations.AddField(
            model_name='condicioneshogar',
            name='motivacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='condicioneshogar',
            name='otras_mascotas',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='condicioneshogar',
            name='propiedad_vivienda',
            field=models.CharField(choices=[('PROPIA', 'Propia'), ('ALQUILADA', 'Alquilada')], default='PROPIA', max_length=15),
        ),
        migrations.AddField(
            model_name='condicioneshogar',
            name='tamano_hogar',
            field=models.CharField(choices=[('PEQUENO', 'Pequeño (< 50 m²)'), ('MEDIANO', 'Mediano (50–120 m²)'), ('GRANDE', 'Grande (> 120 m²)')], default='MEDIANO', max_length=10),
        ),
        migrations.AddField(
            model_name='condicioneshogar',
            name='tiempo_solo_horas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='condicioneshogar',
            name='tiene_ninos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familia',
            name='cedula',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='familia',
            name='direccion',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='familia',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familia',
            name='foto_cedula',
            field=models.ImageField(blank=True, null=True, upload_to='cedulas/'),
        ),
        migrations.AddField(
            model_name='familia',
            name='redes_sociales',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
