# Generated by Django 5.0.6 on 2026-03-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0003_condicioneshogar_ingresos_estimados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='foto_cedula',
        ),
        migrations.AddField(
            model_name='familia',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
