# Generated by Django 5.0.6 on 2026-03-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0004_remove_familia_edad_remove_familia_foto_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
