# Generated by Django 5.0.6 on 2026-03-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('OTRO', 'Otro')], max_length=10)),
                ('raza', models.CharField(blank=True, max_length=100)),
                ('edad_anios', models.PositiveSmallIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_PROCESO', 'En proceso de adopción'), ('ADOPTADO', 'Adoptado'), ('NO_DISPONIBLE', 'No disponible')], default='DISPONIBLE', max_length=15)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'db_table': 'mascotas',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
