# Generated by Django 5.0.6 on 2026-03-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='edad_unidad',
            field=models.CharField(choices=[('ANIOS', 'Años'), ('MESES', 'Meses')], default='ANIOS', max_length=6),
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='historia_mascota',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='historial_vacunas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='info_adicional',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='nivel_energia',
            field=models.CharField(blank=True, choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], max_length=6),
        ),
        migrations.AddField(
            model_name='mascota',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(blank=True, choices=[('MACHO', 'Macho'), ('HEMBRA', 'Hembra')], max_length=6),
        ),
        migrations.AddField(
            model_name='mascota',
            name='tamano',
            field=models.CharField(blank=True, choices=[('PEQUENO', 'Pequeño'), ('MEDIANO', 'Mediano'), ('GRANDE', 'Grande')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('CONEJO', 'Conejo'), ('HAMSTER', 'Hámster')], max_length=10),
        ),
    ]
