# Generated by Django 5.0.6 on 2026-03-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_mascota_edad_unidad_mascota_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='carnet_vacunas',
            field=models.FileField(blank=True, null=True, upload_to='carnets/'),
        ),
        # Convert all existing free-text values to empty JSON array (old format was plain text)
        migrations.RunSQL(
            "UPDATE mascotas SET historial_vacunas = '[]';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='mascota',
            name='historial_vacunas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
