# Generated by Django 5.0.6 on 2026-03-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_mascota_carnet_vacunas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='apta_ninos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='costo_estimado_mensual',
            field=models.CharField(blank=True, choices=[('MENOS_1SMLV', 'Menos de 1 SMLV mensual'), ('1_2SMLV', '1–2 SMLV mensual'), ('2_4SMLV', '2–4 SMLV mensual'), ('MAS_4SMLV', 'Más de 4 SMLV mensual')], max_length=30),
        ),
        migrations.AddField(
            model_name='mascota',
            name='nivel_complejidad',
            field=models.CharField(blank=True, choices=[('BAJO', 'Baja (ideal para principiantes)'), ('MEDIO', 'Media (algo de experiencia recomendada)'), ('ALTO', 'Alta (requiere experiencia)')], max_length=6),
        ),
        migrations.AddField(
            model_name='mascota',
            name='nivel_independencia',
            field=models.CharField(blank=True, choices=[('BAJO', 'Baja (necesita compañía constante)'), ('MEDIO', 'Media (puede estar solo moderadamente)'), ('ALTO', 'Alta (muy independiente)')], max_length=6),
        ),
        migrations.AddField(
            model_name='mascota',
            name='nivel_sociabilidad',
            field=models.CharField(blank=True, choices=[('BAJO', 'Baja (prefiere estar solo)'), ('MEDIO', 'Media (se adapta)'), ('ALTO', 'Alta (muy sociable con otros animales)')], max_length=6),
        ),
    ]
